// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByje3UgfKj6GFqME8GcuLPDmX6SLuTfuk',
    appId: '1:162963359911:web:d536df79301015f5dfb382',
    messagingSenderId: '162963359911',
    projectId: 'ojt-tracking-app-project',
    authDomain: 'ojt-tracking-app-project.firebaseapp.com',
    databaseURL: 'https://ojt-tracking-app-project-default-rtdb.firebaseio.com',
    storageBucket: 'ojt-tracking-app-project.firebasestorage.app',
    measurementId: 'G-N9T29DEXK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjMRLxE3yPqTVAHsE5UFe2MQETDro217U',
    appId: '1:162963359911:android:6977ef710229fb27dfb382',
    messagingSenderId: '162963359911',
    projectId: 'ojt-tracking-app-project',
    databaseURL: 'https://ojt-tracking-app-project-default-rtdb.firebaseio.com',
    storageBucket: 'ojt-tracking-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAVqHxeC2R7LS9odEBm-syt_O6upXfv_A',
    appId: '1:162963359911:ios:52f13551208289a8dfb382',
    messagingSenderId: '162963359911',
    projectId: 'ojt-tracking-app-project',
    databaseURL: 'https://ojt-tracking-app-project-default-rtdb.firebaseio.com',
    storageBucket: 'ojt-tracking-app-project.firebasestorage.app',
    iosClientId: '162963359911-qabpvh7uvuh0nk86saralli8bb7ichap.apps.googleusercontent.com',
    iosBundleId: 'com.example.ojtTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAVqHxeC2R7LS9odEBm-syt_O6upXfv_A',
    appId: '1:162963359911:ios:52f13551208289a8dfb382',
    messagingSenderId: '162963359911',
    projectId: 'ojt-tracking-app-project',
    databaseURL: 'https://ojt-tracking-app-project-default-rtdb.firebaseio.com',
    storageBucket: 'ojt-tracking-app-project.firebasestorage.app',
    iosClientId: '162963359911-qabpvh7uvuh0nk86saralli8bb7ichap.apps.googleusercontent.com',
    iosBundleId: 'com.example.ojtTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByje3UgfKj6GFqME8GcuLPDmX6SLuTfuk',
    appId: '1:162963359911:web:2efe7c85a7a76777dfb382',
    messagingSenderId: '162963359911',
    projectId: 'ojt-tracking-app-project',
    authDomain: 'ojt-tracking-app-project.firebaseapp.com',
    databaseURL: 'https://ojt-tracking-app-project-default-rtdb.firebaseio.com',
    storageBucket: 'ojt-tracking-app-project.firebasestorage.app',
    measurementId: 'G-Z3TVEHLK3L',
  );

}